In [230]:
row

filename      F0107_IND_D2_27_0_01.JPG
forehead                          -1.0
right_eye                          0.0
left_eye                           0.0
nasolabial                         1.0
periroal                           0.0
right_vol                          0.0
left_vol                           0.0
Name: 637, dtype: object

In [ ]:
# 1006 기준 기존 annot 있는 데이터: 028, 030
# 추가 데이터: 045
import pandas as pd
import re

'''
------------------------- json 형식 다른파일이랑 맞췅 -------------------------
[
  {
    "user_id": "0009",
    "image_id": "0009_01",
    "forehead_path": "028_data/data/forehead_0009_01_F.jpg.jpg",
    "right_eye_path": "028_data/data/right_eye_0009_01_F.jpg.jpg",
    "left_eye_path": "028_data/data/left_eye_0009_01_F.jpg.jpg",
    "nasolabial_path": "028_data/data/nasolabial_0009_01_F.jpg.jpg",
    "perioral_path": "028_data/data/perioral_0009_01_F.jpg.jpg",
    "right_vol_path": "028_data/data/right_vol_0009_01_F.jpg.jpg",
    "left_vol_path": "028_data/data/left_vol_0009_01_F.jpg.jpg",
    "forehead": 1,
    "right_eye": 1,
    "left_eye": 1,
    "nasolabial": 3,
    "perioral": 3,
    "right_vol": 1,
    "left_vol": 1
  },
'''


csv_path = "/home/work/hocheol_dir/workspace/_dataset/annotations/wrinkle/1002_045.가족관계데이터-주름.csv"
df = pd.read_csv(csv_path)

# dataloader에서 continue 조건을 -1로 두었임
df.fillna(-1, inplace=True)
df['user_id'] = df['filename'].apply(lambda x: re.search(r"F[0-9]+_IND_[A-Z]+[0-9]*_[0-9]+", x).group())
# df = df[['user_id', 'filename', 'right_cheek', 'left_cheek']]

df.head()

,filename,forehead,right_eye,left_eye,nasolabial,periroal,right_vol,left_vol,user_id
0,F0001_IND_D_18_0_01.JPG,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,F0001_IND_D_18
1,F0001_IND_D_18_0_02.JPG,0.0,0.0,0.0,0.0,0.0,1.0,1.0,F0001_IND_D_18
2,F0001_IND_GM_75_0_01.JPG,3.0,2.0,2.0,3.0,3.0,3.0,3.0,F0001_IND_GM_75
3,F0001_IND_GM_75_0_02.JPG,3.0,2.0,2.0,3.0,3.0,3.0,3.0,F0001_IND_GM_75
4,F0001_IND_M_45_0_01.JPG,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,F0001_IND_M_45

In [251]:
cols = df.columns[1:-1]
valid_df = df[df.apply(lambda row: any(row[cols] != -1), axis=1)]
valid_df[cols] = valid_df[cols].astype(int)
valid_df.rename(columns={'periroal': 'perioral'}, inplace=True)
valid_df

,filename,forehead,right_eye,left_eye,nasolabial,perioral,right_vol,left_vol,user_id
1,F0001_IND_D_18_0_02.JPG,0,0,0,0,0,1,1,F0001_IND_D_18
2,F0001_IND_GM_75_0_01.JPG,3,2,2,3,3,3,3,F0001_IND_GM_75
3,F0001_IND_GM_75_0_02.JPG,3,2,2,3,3,3,3,F0001_IND_GM_75
5,F0001_IND_M_45_0_02.JPG,1,1,1,2,0,2,2,F0001_IND_M_45
6,F0001_IND_M_45_0_05.JPG,1,1,1,2,0,2,2,F0001_IND_M_45
...,...,...,...,...,...,...,...,...,...
1815,F0897_IND_M_50_0_02.JPG,2,1,2,2,2,1,1,F0897_IND_M_50
1816,F0898_IND_D2_14_0_02.JPG,0,0,0,1,0,0,0,F0898_IND_D2_14
1817,F0898_IND_D_19_0_02.JPG,0,0,0,1,0,0,0,F0898_IND_D_19
1818,F0898_IND_F_50_0_02.JPG,3,3,3,2,0,1,2,F0898_IND_F_50
1819,F0899_IND_M_47_0_02.JPG,3,2,2,2,1,1,1,F0899_IND_M_47

In [252]:
import os
import json

json_data = []

for i, row in valid_df.iterrows():
    user_id = row['user_id']
    json_data.append({
        'user_id': row['user_id'],
        'filename': row['filename'],
        "forehead_path": f"045_data/data/forehead_{row['filename']}",
        "right_eye_path": f"045_data/data/right_eye_{row['filename']}",
        "left_eye_path": f"045_data/data/left_eye_{row['filename']}",
        "nasolabial_path": f"045_data/data/nasolabial_{row['filename']}",
        "perioral_path": f"045_data/data/perioral_{row['filename']}",
        "right_vol_path": f"045_data/data/right_vol_{row['filename']}",
        "left_vol_path": f"045_data/data/left_vol_{row['filename']}",
        "forehead": row['forehead'],
        "right_eye": row['right_eye'],
        "left_eye": row['left_eye'],
        "nasolabial": row['nasolabial'],
        "perioral": row['perioral'],
        "right_vol": row['right_vol'],
        "left_vol": row['left_vol']
    })

# import random
# random.sample(json_data, 3)

label_path = '/home/work/hocheol_dir/workspace/_dataset/datasets/wrinkle_data/v0.3/v0.3.0/045_data/label/wrinkle_labels.json'

os.makedirs(os.path.dirname(label_path), exist_ok=True)
with open(label_path, 'w') as f:
    json.dump(json_data, f, indent=2, ensure_ascii=False)