In [13]:
# 1002 기준 기존 annot 있는 데이터: 028, 030, 034, 045, 118, 999
# 추가 데이터: 117
import pandas as pd

'''
------------------------- json 형식 다른파일이랑 맞췅 -------------------------
[
  {
    "user_id": "0001",
    "equipment": 1,
    "left_path": "028_data/data/left_0001_01_F.jpg",
    "right_path": "028_data/data/right_0001_01_F.jpg",
    "left_label": 2,
    "right_label": 2
  },
'''


csv_path = "/home/work/hocheol_dir/workspace/_dataset/annotations/pigment/1002_117.face_parsing-색소.csv"
df = pd.read_csv(csv_path)
df['user_id'] = df['id'].apply(lambda x: f"{x:04d}")
df = df[['user_id', 'filename', 'right_cheek', 'left_cheek']]

df.head()

,user_id,filename,right_cheek,left_cheek
0,0031,0031_direct_indoor_normal_00000009.png,NaN,NaN
1,0031,0031_direct_indoor_normal_00000011.png,NaN,NaN
2,0031,0031_direct_outdoor_back_normal_00000020.png,NaN,NaN
3,0031,0031_direct_outdoor_direct_normal_00000023.png,NaN,NaN
4,0031,0031_wild_indoor_normal_00000040.png,0.0,1.0

In [29]:
# 전처리 할 데이터 필터링 : right_cheek, left_cheek 하나라도 class 있는 데이터 그냥 양쪽 다 해놓자
valid_df = df[df['right_cheek'].notna() | df['left_cheek'].notna()].reset_index(drop=True)
valid_df['right_cheek'] = valid_df['right_cheek'].fillna(-1)
valid_df['left_cheek'] = valid_df['left_cheek'].fillna(-1)

valid_df['right_cheek'] = valid_df['right_cheek'].astype(int)
valid_df['left_cheek'] = valid_df['left_cheek'].astype(int)
valid_df.head()

  user_id                               filename  right_cheek  left_cheek
0    0031   0031_wild_indoor_normal_00000040.png            0           1
1    0035   0035_wild_indoor_normal_00000041.png            2           2
2    0035  0035_wild_outdoor_normal_00000048.png            2           2
3    0036   0036_wild_indoor_normal_00000041.png            1           1
4    0036  0036_wild_outdoor_normal_00000046.png            1           1

In [49]:
import os
import json

json_data = []

for i, row in valid_df.iterrows():
    user_id = row['user_id']
    json_data.append({
        'user_id': row['user_id'],
        'filename': row['filename'],
        'left_path': f"117_data/data/left_{row['filename']}",
        'right_path': f"117_data/data/right_{row['filename']}",
        'left_label': row['left_cheek'],
        'right_label': row['right_cheek']
    })

# import random
# random.sample(json_data, 3)

label_path = '/home/work/hocheol_dir/workspace/_dataset/datasets/pigment_data/v0.4/v0.4.0/117_data/label/pig_label_paths.json'

os.makedirs(os.path.dirname(label_path), exist_ok=True)
with open(label_path, 'w') as f:
    json.dump(json_data, f, indent=2, ensure_ascii=False)